#

pluginName = labour Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_BoulderingWall_type = Bouldering Wall
_UI_Hold_type = Hold
_UI_Route_type = Route
_UI_Volume_type = Volume
_UI_Circle_type = Circle
_UI_Triangle_type = Triangle
_UI_Position_type = Position
_UI_RouteStep_type = Route Step
_UI_HoldStep_type = Hold Step
_UI_SplitStep_type = Split Step
_UI_AngularPosition_type = Angular Position
_UI_CartesianPosition_type = Cartesian Position
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_BoulderingWall_holds_feature = Holds
_UI_BoulderingWall_routes_feature = Routes
_UI_BoulderingWall_volumes_feature = Volumes
_UI_BoulderingWall_ID_feature = ID
_UI_Hold_identifier_feature = Identifier
_UI_Hold_pos_feature = Pos
_UI_Hold_shape_identifier_feature = Shape identifier
_UI_Hold_rotation_feature = Rotation
_UI_Hold_colours_feature = Colours
_UI_Hold_start_hold_feature = Start hold
_UI_Hold_end_hold_feature = End hold
_UI_Route_grade_feature = Grade
_UI_Route_identifier_feature = Identifier
_UI_Route_grid_base_point_feature = Grid base point
_UI_Route_holds_feature = Holds
_UI_Volume_depth_feature = Depth
_UI_Volume_pos_feature = Pos
_UI_Circle_radius_feature = Radius
_UI_Circle_side_holds_feature = Side holds
_UI_Circle_front_holds_feature = Front holds
_UI_Triangle_corners_feature = Corners
_UI_Triangle_extrusion_feature = Extrusion
_UI_Triangle_left_holds_feature = Left holds
_UI_Triangle_right_holds_feature = Right holds
_UI_Triangle_bottom_holds_feature = Bottom holds
_UI_HoldStep_hold_feature = Hold
_UI_SplitStep_left_feature = Left
_UI_SplitStep_right_feature = Right
_UI_AngularPosition_angle_feature = Angle
_UI_CartesianPosition_x_feature = X
_UI_CartesianPosition_y_feature = Y
_UI_Unknown_feature = Unspecified

_UI_Colour_red_literal = red
_UI_Colour_blue_literal = blue
_UI_Colour_green_literal = green
_UI_Colour_yellow_literal = yellow
_UI_Colour_black_literal = black
_UI_Colour_purple_literal = purple
_UI_Colour_white_literal = white
_UI_Colour_orange_literal = orange
_UI_Colour_pink_literal = pink
