#

pluginName = nl.tue.dsldesign.turtle Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Program_type = Program
_UI_Statement_type = Statement
_UI_Move_type = Move
_UI_TurnLeft_type = Turn Left
_UI_TurnRight_type = Turn Right
_UI_TurnToZero_type = Turn To Zero
_UI_If_type = If
_UI_Assignment_type = Assignment
_UI_Expr_type = Expr
_UI_Unary_type = Unary
_UI_Binary_type = Binary
_UI_Sqr_type = Sqr
_UI_Sqrt_type = Sqrt
_UI_Arctan_type = Arctan
_UI_Abs_type = Abs
_UI_VarRef_type = Var Ref
_UI_RealConst_type = Real Const
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Program_statements_feature = Statements
_UI_Move_expr_feature = Expr
_UI_TurnLeft_expr_feature = Expr
_UI_TurnRight_expr_feature = Expr
_UI_If_cond_feature = Cond
_UI_If_then_feature = Then
_UI_If_else_feature = Else
_UI_Assignment_var_feature = Var
_UI_Assignment_expr_feature = Expr
_UI_Unary_expr_feature = Expr
_UI_Binary_left_feature = Left
_UI_Binary_right_feature = Right
_UI_Binary_operation_feature = Operation
_UI_VarRef_var_feature = Var
_UI_RealConst_value_feature = Value
_UI_Unknown_feature = Unspecified

_UI_Operation_LT_literal = LT
_UI_Operation_DIVISION_literal = DIVISION
_UI_Operation_MULTI_literal = MULTI
_UI_Operation_ADD_literal = ADD
_UI_Operation_SUBTRACT_literal = SUBTRACT
_UI_Operation_EQ_literal = EQ
